#!/bin/sh

set -e

SUPPORTED_IMPLS="ikarus mzscheme guile ypsilon"
REQUIRED_LIBS="srfi spells/spells industria/weinholt ocelotl dorodango"
REQUIRED_WAK_LIBS="common irregex fmt foof-loop parscheme syn-param riastreams"
LIBS_DIR="`pwd`/../_libs"

missing_prerequisite() {
    echo "ERROR: prerequisite $1 not found in parent directory."
    exit 1
}

setup_symlinks() {
    exclude_rx="$1"
    rm -rf "$LIBS_DIR"
    mkdir -p "$LIBS_DIR"
    for lib in $REQUIRED_LIBS; do
        if ! echo "$lib" | grep -q "$exclude_rx"; then
            [ -d "../$lib" ] || missing_prerequisite "$lib"
            ln -s "../$lib" "$LIBS_DIR/"
        fi
    done
    mkdir -p "$LIBS_DIR/wak"
    for lib in $REQUIRED_WAK_LIBS; do
        if ! echo "wak-$lib" | grep -q "$exclude_rx"; then
            [ -d "../wak-$lib" ] ||  missing_prerequisite "wak-$lib"
            ( cd "../wak-$lib" && find . \( -name "*.sls" ! -path "*/_darcs/*" \) \
                -o \( -name "*.scm" -a ! -path "*/test/*" -a ! -path "*/_darcs/*" \
                -a ! -name pkg-list.scm \) \
                | tar -c -T - ) \
                | tar -C "$LIBS_DIR/wak" -x
        fi
    done
}

impl_setup() {
    impl="$1"
    case "$impl" in
        ikarus|ypsilon|mosh)
            setup_symlinks '^$'
            ;;
        mzscheme|guile)
            setup_symlinks '^srfi$'
            ;;
        *)
            echo "Unsupported implementation '$impl'; patches welcome ;-)"
            exit 1
            ;;
    esac
}

IMPL=none
while true; do
    case "$1" in
        -i|--implementation)
            shift; IMPL="$1"; shift
            ;;
        *)
            break
    esac
done

if [ "$IMPL" = none ]; then
    for impl in $SUPPORTED_IMPLS; do
        if command -v "$impl" > /dev/null; then
            IMPL="$impl"
            break
        fi
    done
    if [ "$IMPL" = none ]; then
        echo "Error: no supported implementation found in PATH" >&2
        echo "You need one of ($SUPPORTED_IMPLS) installed" >&2
    fi
fi

export R6RS_LIBRARY_PATH="$LIBS_DIR"

echo "* Using $IMPL"
impl_setup "$IMPL"
runner="scripts/r6rs-script.$IMPL"

case "$1" in
    dist)
        $runner scripts/maint.sps "$@"
        ;;
    *)
        echo "* Installing dorodango"
        $runner scripts/doro.sps "$@" --no-config --non-interactive install --bundle ..  dorodango
esac
