#!/bin/sh

set -e

SUPPORTED_IMPLS="ikarus ypsilon"
REQUIRED_LIBS="srfi spells/spells parscheme/parscheme industria/weinholt ocelotl dorodango"
LIBS_DIR="`pwd`/../_libs"

setup_symlinks() {
    exclude_rx="$1"
    mkdir -p "$LIBS_DIR"
    find "$LIBS_DIR" -type l -delete
    for lib in $REQUIRED_LIBS; do
        if ! echo "$lib" | grep -q "$exclude_rx"; then
            ln -s "../$lib" "$LIBS_DIR/"
        fi
    done
}

impl_setup() {
    impl="$1"
    case "$impl" in
        ikarus|ypsilon|mosh)
            setup_symlinks '^$'
            ;;
        plt)
            setup_symlinks '^srfi$'
            ;;
        *)
            echo "Unsupported implementation '$impl'; patches welcome ;-)"
            exit 1
            ;;
    esac
}

IMPL=none
while true; do
    case "$1" in
        -i) shift; IMPL="$1"; shift
            ;;
        *)
            break
    esac
done

if [ "$IMPL" = none ]; then
    for impl in $SUPPORTED_IMPLS; do
        if command -v "$impl" > /dev/null; then
            IMPL="$impl"
            break
        fi
    done
    if [ "$IMPL" = none ]; then
        echo "Error: no supported implementation found in PATH" >&2
        echo "You need one of ($SUPPORTED_IMPLS) installed" >&2
    fi
fi

export R6RS_LIBRARY_PATH="$LIBS_DIR"

echo "* Using $IMPL"
impl_setup "$IMPL"
runner="scripts/r6rs-script.$IMPL"

case "$1" in
    dist)
        $runner scripts/maint.sps "$@"
        ;;
    *)
        echo "* Installing dorodango"
        $runner scripts/doro.sps "$@" init --implementation "$IMPL"
        $runner scripts/doro.sps "$@" --no-config install --bundle ..  dorodango
esac
